services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    image: spe-dev
    command: -Dspring-boot.run.profiles=dev
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - path: ./src
          action: sync+restart
          target: /app/src
    environment:
      DATABASE_URL: "postgresql://postgres/${DATABASE_NAME}?user=${DATABASE_USER:-postgres}&password=${DATABASE_PASSWORD}"
      JWT_SECRET: ${JWT_SECRET}
      JWT_DURATION: ${JWT_DURATION}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  postgres-data: